// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AsmUIClient is the client API for AsmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsmUIClient interface {
	// ListSidecarSpecs returns a list of Service Sidecar(s) that can be started through the UI.
	ListSidecarSpecs(ctx context.Context, in *ListSidecarSpecsRequest, opts ...grpc.CallOption) (AsmUI_ListSidecarSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type asmUIClient struct {
	cc grpc.ClientConnInterface
}

func NewAsmUIClient(cc grpc.ClientConnInterface) AsmUIClient {
	return &asmUIClient{cc}
}

func (c *asmUIClient) ListSidecarSpecs(ctx context.Context, in *ListSidecarSpecsRequest, opts ...grpc.CallOption) (AsmUI_ListSidecarSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AsmUI_ServiceDesc.Streams[0], "/v1.AsmUI/ListSidecarSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &asmUIListSidecarSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AsmUI_ListSidecarSpecsClient interface {
	Recv() (*ListSidecarSpecsResponse, error)
	grpc.ClientStream
}

type asmUIListSidecarSpecsClient struct {
	grpc.ClientStream
}

func (x *asmUIListSidecarSpecsClient) Recv() (*ListSidecarSpecsResponse, error) {
	m := new(ListSidecarSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *asmUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.AsmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsmUIServer is the server API for AsmUI service.
// All implementations must embed UnimplementedAsmUIServer
// for forward compatibility
type AsmUIServer interface {
	// ListSidecarSpecs returns a list of Service Sidecar(s) that can be started through the UI.
	ListSidecarSpecs(*ListSidecarSpecsRequest, AsmUI_ListSidecarSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedAsmUIServer()
}

// UnimplementedAsmUIServer must be embedded to have forward compatible implementations.
type UnimplementedAsmUIServer struct {
}

func (UnimplementedAsmUIServer) ListSidecarSpecs(*ListSidecarSpecsRequest, AsmUI_ListSidecarSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSidecarSpecs not implemented")
}
func (UnimplementedAsmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedAsmUIServer) mustEmbedUnimplementedAsmUIServer() {}

// UnsafeAsmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsmUIServer will
// result in compilation errors.
type UnsafeAsmUIServer interface {
	mustEmbedUnimplementedAsmUIServer()
}

func RegisterAsmUIServer(s grpc.ServiceRegistrar, srv AsmUIServer) {
	s.RegisterService(&AsmUI_ServiceDesc, srv)
}

func _AsmUI_ListSidecarSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSidecarSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AsmUIServer).ListSidecarSpecs(m, &asmUIListSidecarSpecsServer{stream})
}

type AsmUI_ListSidecarSpecsServer interface {
	Send(*ListSidecarSpecsResponse) error
	grpc.ServerStream
}

type asmUIListSidecarSpecsServer struct {
	grpc.ServerStream
}

func (x *asmUIListSidecarSpecsServer) Send(m *ListSidecarSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AsmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AsmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AsmUI_ServiceDesc is the grpc.ServiceDesc for AsmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AsmUI",
	HandlerType: (*AsmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _AsmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListSidecarSpecs",
			Handler:       _AsmUI_ListSidecarSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "asm-ui.proto",
}
